config/routes.rb
Rails.application.routes.draw do

  get 'users/index'
  resources :users  , only: [:destroy]
  resources :tags , only: [:index , :show]
  get 'index' , :controller => :answers
  devise_for :users
  devise_scope :user do
    get "login", to: "devise/sessions#new", as: :login
    delete "logout", to: "devise/sessions#destroy", as: :logout
  end

  root 'questions#index'
  resources :profile, only: [:show, :edit, :update]
  resources :questions  
  resources :answers  do 
    member do 
      put "like" , to: "answers#upvote"
      put "dislike" , to: "answers#downvote"
    end
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	acts_as_votable 
	belongs_to :user
	belongs_to :question

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>", :gavatar => "50x50"}, :default_url => ActionController::Base.helpers.asset_path('user-icon.png')
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def full_name
    first_name + " " + last_name 
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :content, presence: true #Boş geçilmesin
  validates :title, length: {maximum: 50}
  has_many :answers , dependent: :destroy
  belongs_to :user
  is_impressionable
  has_and_belongs_to_many :tags
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :questions
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :answers , dependent: :destroy
  has_many :questions , dependent: :destroy
  has_one :profile , dependent: :destroy
  has_and_belongs_to_many :roles
  after_create :make_profile , on: :create 
  before_create :set_default_role
  def set_default_role
    self.roles << Role.last
  end
  
  def make_profile
    create_profile(
      first_name: "İsimsiz Kullanıcı",
      last_name: "",
      phone: ""
    )
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	before_action :authenticate_user! , except: [:index]
	before_action :set_answer , except: [:create , :new , :index]

	def index
		@answers = Answer.all
	end

	def create
		@answer = Answer.new(answer_params)
		@answer.user = current_user
		if @answer.save
		  redirect_to question_path(@answer.question_id) , notice: "cevabiniz basari ile kaydedildi."
		else
		  redirect_to question_path(@answer.question_id) , alert: "Bir hata olustu"
		end
	end

	def edit
	end

	def update
		redirect_to question_path(@answer.question_id) , alert: "yetkisiz erisim" unless permitted
		if @answer.update(answer_params)
			redirect_to question_path(@answer.question_id)
		else
			render 'edit'
		end
		
	end

	def destroy
		redirect_to question_path(@answer.question_id) , alert: "yetkisiz erisim" unless permitted
		if @answer.destroy
			flash[:success] = "Cevap Silindi"
			redirect_to question_path(@answer.question_id)
		else
			flash[:success] = "Cevap Silinemedi"
		end
	end

	def upvote
		@answer = Answer.find(params[:id])
		@answer.upvote_by current_user
		if reputation(@answer) > 10
			@answer.user.roles.delete(@answer.user.roles.last)
			@answer.user.roles << Role.find_by_role("Moderatör")
		elsif reputation(@answer) > 5
			@answer.user.roles.delete(@answer.user.roles.last)
			@answer.user.roles << Role.find_by_role("Tecrubeli Kullanıcı")
		else
			@answer.user.roles.delete(@answer.user.roles.last)  
			@answer.user.roles << Role.find_by_role("Çaylak")
		end 	 
		redirect_to :back
	end

	def downvote
		@answer = Answer.find(params[:id])
		@answer.downvote_by current_user
		if reputation(@answer) > 10
			@answer.user.roles.delete(@answer.user.roles.last) 
			@answer.user.roles << Role.find_by_role("Moderatör")
		elsif reputation(@answer) > 5
			@answer.user.roles.delete(@answer.user.roles.last)  
			@answer.user.roles << Role.find_by_role("Tecrubeli Kullanıcı")
		else
			@answer.user.roles.delete(@answer.user.roles.last)  
			@answer.user.roles << Role.find_by_role("Çaylak")
		end 	 
		redirect_to :back
	end

	private

	def set_answer
		@answer =Answer.find(params[:id])
	end

	def answer_params
		params.require(:answer).permit(:content , :question_id)
	end
	def permitted
		current_user == @answer.user || current_user.roles.first == Role.first
	end

	def reputation(a)
		total = 0 
 		a.user.answers.each do |x| 
			total += x.votes_for.up.count
		end
		total 
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	if current_user.sign_in_count == 1
  		request.env['omniauth.origin'] || stored_location_for(resource) || edit_profile_path(current_user.profile)
  	else
  		super
  	end	
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_profile

  def show
  end

  def edit
    redirect_to root_path, alert: "Yetkisiz Erişim.." unless permitted?
  end

  def update
    if @profile.update(profile_params)
      redirect_to profile_path(@profile), notice: "Güncelleme Başarılı.."
    end
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def permitted?
    current_user == @profile.user
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :phone, :avatar )
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  impressionist :actions=>[:show]
  impressionist :unique => [:impressionable_id, :session_hash]
  def index
    @questions = Question.order(id: :desc). paginate(:page => params[:page], :per_page => 10)
  end

  def show
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to root_path, notice: "Kayıt Başarılı"
    else
      render :new, alert: "Kayıt işlemi yapılırken bir hata ile karşılaşıldı."
    end
  end

  def edit
    redirect_to root_path, alert: "Yetkisiz Erişim." unless permitted?
  end

  def update
    redirect_to root_path, alert: "Yetkisiz Erişim." unless permitted?
    if @question.update(question_params)
      redirect_to @question
    end

  end

  def destroy
    redirect_to root_path, alert: "Yetkisiz Erişim." unless permitted?
    @question.delete
    redirect_to root_path
  end

  private

  def permitted?
    current_user == @question.user || current_user.roles.first == Role.first
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :content , :tag_ids =>[])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  	@tags = Tag.all
  end

  def show
  	@tag = Tag.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def destroy
  	if current_user.roles.first == Role.first
  		@user = User.find(params[:id])
  		@user.destroy
  		redirect_to root_path
  	else
  		redirect_to root_path ,  alert: "Yetkisiz Erişim."
  	end
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def reputation(a)
		total = 0 
 		a.user.answers.each do |x| 
			total += x.votes_for.up.count
		end
		total 
  end 
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answer.html.erb
<ul>
	<% @question.answers.sort_by {|a| a.votes_for.up.count}.reverse.each do |answer| %>
		<div class="row">
  			<div class="col-md-7">
  				<li><%= answer.content %> &nbsp;
					<% if (user_signed_in? && current_user.id == answer.user.id) || (user_signed_in? &&current_user.roles.first == Role.first) %>
					  <span class="duzenle"><i class="fa fa-pencil"></i><%= link_to "Duzenle" , edit_answer_path(answer),class: "duzenle"%></span>
					  <span class="sil"><i class="fa fa-trash-o"></i><%= link_to "Sil", answer, method: :delete, data: {confirm: "Emin misin?"}, class: "sil" %></span>
					<% end %>
				</li>
  			</div>
  			<div class="col-md-5">
  				<span class="help-block"><i class="fa fa-clock-o"></i> <b><%= link_to time_ago_in_words(answer.created_at)%> <br> 
					<%= image_tag answer.user.profile.avatar.url(:medium), height: '30', width: '30' %>&nbsp;
					<%= link_to answer.user.profile.full_name , profile_path(answer.user.profile) %> <br> 
					Rütbe:<%= answer.user.roles.first.role %> <br>
					Reputation Point:<%= reputation(answer) %></b> <br>
	  				<%= link_to "", like_answer_path(answer) , class: "fa fa-thumbs-o-up" , method: :put %> <b>  <%= answer.get_likes.size %> </b><b>
	  				<%= link_to "", dislike_answer_path(answer) , class: "fa fa-thumbs-o-down",method: :put %><%= answer.get_dislikes.size %></b>
				</span>
			</div>
		</div>
	<% end %>
</ul>

app/views/answers/_form.html.erb
<%= simple_form_for :answer , url: answers_path    do |f| %>
	<%= f.input :content , label: "",   placeholder: "Cevabinizi Yaziniz"  %>
	<%= f.hidden_field :question_id , value: @question.id %>
	<%= f.submit "Kaydet" , class: "btn btn-primary" %>
<% end %>

app/views/answers/edit.html.erb
<%= simple_form_for @answer do |f| %>
  <%= f.input :content, label: "İçerik",  placeholder: "İçeriği yazınız.." %>
  <%= f.button :submit, "Kaydet" %>
<% end %>
<%= link_to "Geri" , question_path(@answer.question) , class: "btn btn-warning"  %>

app/views/answers/index.html.erb
<ul class="list-group">
  <% if @answers.count > 0 %>
    <% @answers.sort_by {|a| a.votes_for.up.count}.reverse.each do |answer| %>
      <ul class="list-group">
        <li class="list-group-item"><%= link_to answer.content , question_path(answer.question) %> &nbsp;
          <i class="fa fa-user"></i>&nbsp;<%= link_to answer.user.profile.full_name , profile_path(answer.user.profile) %>&nbsp;
          <% if (user_signed_in?) && (current_user.id == answer.user.id) %>
            <span class="duzenle"><i class="fa fa-pencil"></i><%= link_to "Duzenle" , edit_answer_path(answer),class: "duzenle"%></span>
            <span class="sil"><i class="fa fa-trash-o"></i><%= link_to "Sil", answer, method: :delete, data: {confirm: "Emin misin?"}, class: "sil" %></span>
          <% end %>
          <span class="help-block"><i class="fa fa-clock-o"></i> <%=time_ago_in_words(answer.created_at)%>&nbsp;
          <%= link_to "" , like_answer_path(answer) , method: :put , class: "fa fa-thumbs-o-up"%>&nbsp;<%= answer.votes_for.up.count %>&nbsp;
          <%= link_to "" , dislike_answer_path(answer) , method: :put , class: "fa fa-thumbs-o-down"%>&nbsp;<%= answer.votes_for.down.count %></span>
        </li>
      </ul>
    <% end %>
  <% end %>
</ul>

<%= link_to "Geri", root_path, class: "btn btn-warning" %> <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CengOverFlow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <div class="navbar-brand"><i class="fa fa-stack-overflow"></i> <%= link_to "CengOverFlow", root_path, style: "text-decoration:none;color:inherit" %>
        </div>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Soru Ara</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <% if user_signed_in? %>
              <%= image_tag current_user.profile.avatar(:thumb) , height: '40', width: '50' %>
              <%= current_user.profile.full_name %>
            <% else %>  
              "Misafir Kullanıcı"
            <% end  %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if user_signed_in? %>
                <li><%= link_to "Profilim", profile_path(current_user.profile) %></li>
                <li><%= link_to "Çıkış Yap", logout_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Giriş Yap", login_path %></li>
                <li><%= link_to "Kayıt Ol", new_user_registration_path %></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

<div class="container">
  <div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-body">
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% elsif alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
    <div class="col-md-3">

      <div class="panel panel-default">
        <div class="panel-heading"><h3>Hızlı Erişim</h3></div>
        <div class="panel-body">
          <ul>
              <li><h4><%= link_to "Questions" , root_path  %></h4>
              <li><h4><%= link_to "Tags" ,  tags_path %></h4> </li>
              <li><h4><%= link_to "Users" , users_index_path  %></h4>
              <li><h4><%= link_to "Answers" , answers_path  %></h4>
              </li>
          </ul>    
        </div>
      </div>
    </div> 
  </div>
</div>
</body>
</html>

app/views/questions/_form.html.erb
<%= simple_form_for @question do |f| %>
  <%= f.input :title, label: 'Başlık' %>
  <%= f.input :content, label: "İçerik",  placeholder: "İçeriği yazınız.." %>
  <%= f.association :tags , as: :check_boxes %>
  <%= f.button :submit, "Kaydet" , class: "btn btn-success" %>
<% end %>

app/views/questions/edit.html.erb
<%= render 'form' %>
<%= link_to "Geri" , root_path , class: "btn btn-warning" %>

app/views/questions/index.html.erb
<ul class="list-group">
  <% if @questions.count > 0  %>
    <% @questions.each do |question| %>
      <li class="list-group-item">
        <% question.tags.each do |tag| %>
          <span class="badge"><%= link_to tag.title , tag%></span>
        <% end %>
        <%= link_to question.title, question %>
        <% if (user_signed_in? && current_user == question.user) || (user_signed_in? &&current_user.roles.first == Role.first) %>
          <span class="duzenle"><i class="fa fa-pencil"></i> <%= link_to "Düzenle", edit_question_path(question), class: "duzenle" %> </span>
          <span class="sil"><i class="fa fa-trash-o"></i> <%= link_to "Sil", question, method: :delete, data: {confirm: "Emin misin?"}, class: "sil" %></span>
        <% end %><br>
        <small class="help-block"><i class="fa fa-clock-o"></i> <%= time_ago_in_words(question.created_at)%>&nbsp;&nbsp;&nbsp;<i class="fa fa-user"></i> <%= link_to question.user.profile.full_name , profile_path(question.user)%>&nbsp;&nbsp;&nbsp;<i class="fa fa-commenting-o"></i>&nbsp;<%= question.answers.count%>&nbsp;&nbsp;&nbsp;<i class="fa fa-eye"></i>&nbsp;<%= question.impressionist_count(:filter => :user_id) %></small>
      </li>
    <% end %>
  <% end %>
  <%= will_paginate @questions %>
</ul>
<%= link_to "Yeni Soru Sor", new_question_path, class: "btn btn-primary" if current_user%>

app/views/questions/new.html.erb
<%= render 'form' %>
<%= link_to "Geri", root_path, class: "btn btn-warning" %> <br>

app/views/questions/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
  
    <h2><%= @question.title %></h2>
  </div>
  <div class="panel-body">
  <h4><%= @question.content %></h4>
    <div class="row">
    <div class="col-md-7"></div>
      <div class="col-md-5">
       <% @question.tags.each do |tag| %>
     <span class="badge"><%= link_to tag.title , tag%></span>
     <% end %>
        <span class="help-block"><i class="fa fa-clock-o"></i> <b><%=time_ago_in_words(@question.created_at)%> <br> </b> </span>
        <%= image_tag @question.user.profile.avatar.url(:medium), height: '30', width: '30' %>&nbsp;
        <%= link_to @question.user.profile.full_name , profile_path(@question.user.profile) %> <br> 
        Rütbe:<%= @question.user.roles.first.role %> <br>
        Reputation Point:<%= reputation(@question) %></b> <br>
      </div>
    </div>
        
    
     
  </div>
</div>
<div class="panel panel-default">
<div class="panel-heading"><%= render "answers/answer" %></div>
	<div class="panel-body">
	 <%= render "answers/form" %>
  </div>
</div>
 
 

<%= link_to "Geri", root_path, class: "btn btn-warning btn-geri" %>

app/views/tags/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
  	<h1>All Tags</h1>
  </div>
</div>
<% @tags.each do |tag| %>
	<span class="badge"><%= link_to tag.title , tag_path(tag) %></span>
<% end %><br><br>
<%= link_to "Geri", root_path, class: "btn btn-warning" %> <br>

app/views/tags/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Questions with <%= @tag.title %> Tag</h1>
  </div>  
  <ul class="list-group">
    <% @tag.questions.reverse.each do |question| %>
      <li class="list-group-item">
        <% question.tags.each do |tag| %>
          <span class="badge"><%= link_to tag.title , tag%></span>
        <% end %>
        <%= link_to question.title, question %>
        <% if user_signed_in? && current_user == question.user %>&nbsp;&nbsp;&nbsp;
          <span class="duzenle"><i class="fa fa-pencil"></i> <%= link_to "Düzenle", edit_question_path(question), class: "duzenle" %> </span>&nbsp;
          <span class="sil"><i class="fa fa-trash-o"></i> <%= link_to "Sil", question, method: :delete, data: {confirm: "Emin misin?"}, class: "sil" %></span>
        <% end %><br>
        <small class="help-block"><i class="fa fa-clock-o"></i> <%=time_ago_in_words(question.created_at)%>&nbsp;&nbsp;&nbsp;<i class="fa fa-user"></i> <%= link_to question.user.profile.full_name , profile_path(question.user)%>&nbsp;&nbsp;&nbsp;<i class="fa fa-commenting-o"></i>&nbsp;<%= question.answers.count%>&nbsp;&nbsp;&nbsp;<i class="fa fa-eye"></i>&nbsp;<%= question.impressionist_count(:filter => :user_id) %></small>
      </li>
    <% end %>
  </ul>
</div>
<%= link_to "Geri", tags_path, class: "btn btn-warning" %> <br>

app/views/users/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Users</h1>
  </div>
</div>  
<% if @users.count > 0  %>
  <% @users.each_slice(2) do |users| %>
  	<div class="row">
  		<% users.each do |user| %>
    		<div class="col-md-6">
          <%= link_to profile_path(user) do  %>
    				<%= image_tag user.profile.avatar.url(:medium), height: '126', width: '185' %> <br>
          <% end %>  
    			<h4><%= link_to user.profile.full_name, profile_path(user) %></h2>
    		</div>				 
  		<% end %>
  	</div>
  <% end %>
<% end %>
<%= link_to "Geri", root_path, class: "btn btn-warning" %> <br>